# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_echo', models.CharField(max_length=255, unique=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('program_counter', models.IntegerField(default=1)),
                ('end', models.BooleanField(default=False)),
                ('is_in_conditional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalSession',
            fields=[
                ('appsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='session.AppSession')),
                ('current_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.ConditionalHeader')),
            ],
            bases=('session.appsession',),
        ),
        migrations.AddField(
            model_name='appsession',
            name='current_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='appsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appsession',
            name='conditional_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_session', to='session.ConditionalSession'),
        ),
    ]
