# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='program_counter',
            field=models.IntegerField(default=1),
        ),
    ]
