# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_appsession_is_entering_conditional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalsession',
            name='current_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.Recipe'),
        ),
    ]
