# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0007_auto_20160322_2103'),
        ('session', '0002_auto_20160316_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalSession',
            fields=[
                ('appsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='session.AppSession')),
                ('current_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipes.ConditionalHeader')),
            ],
            bases=('session.appsession',),
        ),
        migrations.AddField(
            model_name='appsession',
            name='is_in_conditional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsession',
            name='conditional_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_session', to='session.ConditionalSession'),
        ),
    ]
