# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20160414_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsession',
            name='amazon_echo',
            field=models.CharField(max_length=255),
        ),
    ]
