# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnStatement', models.TextField()),
                ('NextAction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recipes.GeneralAction')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('FirstAction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Recipes.GeneralAction')),
            ],
        ),
    ]
