# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='parent_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='Recipes.ConditionalHeader'),
        ),
        migrations.AddField(
            model_name='generalaction',
            name='api_call',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_action', to='Recipes.APICall'),
        ),
        migrations.AddField(
            model_name='generalaction',
            name='basic_return_text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_action', to='Recipes.BasicReturnText'),
        ),
        migrations.AddField(
            model_name='generalaction',
            name='conditional',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_action', to='Recipes.ConditionalHeader'),
        ),
        migrations.AddField(
            model_name='generalaction',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='Recipes.Recipe'),
        ),
    ]
