# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_auto_20160325_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalheader',
            name='question',
            field=models.TextField(default="I'm Ron Bugundy???"),
            preserve_default=False,
        ),
    ]
