# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0005_auto_20160313_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('is_get', models.BooleanField(default=True)),
                ('json_string', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='generalaction',
            name='is_api_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='generalaction',
            name='basic_return_text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_action', to='Recipes.BasicReturnText'),
        ),
        migrations.AlterField(
            model_name='generalaction',
            name='type',
            field=models.CharField(choices=[('NS', 'Not Specified'), ('RT', 'Basic Return Text')], default='RT', max_length=2),
        ),
        migrations.AddField(
            model_name='generalaction',
            name='api_call',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_action', to='Recipes.APICall'),
        ),
    ]
